#!/usr/bin/env bash
#Creates file in /var/run/myscript.pid containing its PID
#

echo "$$" > /var/run/myscript.pid

termfunc() {
  rm /var/run/myscript.pid
  exit
}


while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && termfunc' SIGTERM
  trap 'termfunc' SIGQUIT
done
